
CREATE TABLE IF NOT EXISTS {PREFIX}fifu_alt (
    hash CHAR(32) NOT NULL PRIMARY KEY,
    alt        TEXT     NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
                                   ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB {CHARSET_COLLATE};
