CREATE TABLE IF NOT EXISTS {PREFIX}fifu_invalid_media_su (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    md5 VARCHAR(32) NOT NULL,
    attempts INT NOT NULL,
    UNIQUE KEY md5 (md5)
) ENGINE=InnoDB {CHARSET_COLLATE};
